name: E2E Test
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

env:
  DEBUG: replay:cli:*

jobs:
  check:
    # needs: only-doc-changes
    # if: needs.only-doc-changes.outputs.only-doc-changes == 'false'
    name: ✅ Check constraints, dependencies, and package.json's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
        working-directory: ./tasks/check

      - name: ✅ Check constraints, dependencies, and package.json's
        uses: ./tasks/check

  record:
    needs: check
    runs-on: ubuntu-latest
    outputs:
      recordDuration: ${{steps.end.outputs.recordDuration}}
      uploadDuration: ${{steps.end.outputs.uploadDuration}}
    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1
      # This makes sure that playwright dependencies are cached in node_modules.
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Setup job
        uses: ./.github/actions/setup_job
        with:
          node-version: 16

      - name: 🌲 Setup test project
        id: setup_test_project
        uses: ./.github/actions/setup_test_project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium && npx @replayio/playwright install

      - name: Run `rw build` without prerender
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run `rw prerender`
        run: |
          yarn rw prerender --verbose
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Set test start
        if: always()
        id: recordStart
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Run smoke tests on 'rw dev', 'rw serve', 'rw storybook'
        working-directory: ./tasks/smoke-test
        run: npx playwright test --project replay-chromium --reporter=@replayio/playwright/reporter,line
        env:
          PROJECT_PATH: ${{ steps.setup_test_project.outputs.test_project_path }}
          REDWOOD_DISABLE_TELEMETRY: 1
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: Smoke test / ubuntu-latest / node 16 latest
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}

      - name: Set upload start
        if: always()
        id: uploadStart
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Upload Replays
        if: always()
        uses: replayio/action-upload@v0.4.3
        with:
          public: true
          api-key: rwk_RZ7vH8VGJKYQzYpOexaC2IdHRh3GPy0xJcLEUDobdkX
      - name: Set duration in output
        id: end
        if: always()
        run: |
          echo "recordDuration=$((${{ steps.uploadStart.outputs.time }} - ${{ steps.recordStart.outputs.time }}))" >> $GITHUB_OUTPUT
          echo "uploadDuration=$((`date +%s` - ${{ steps.uploadStart.outputs.time }}))" >> $GITHUB_OUTPUT

  no-record:
    needs: check
    runs-on: ubuntu-latest
    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1
      # This makes sure that playwright dependencies are cached in node_modules.
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Setup job
        uses: ./.github/actions/setup_job
        with:
          node-version: 16

      - name: 🌲 Setup test project
        id: setup_test_project
        uses: ./.github/actions/setup_test_project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium && npx @replayio/playwright install

      - name: Run `rw build` without prerender
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run `rw prerender`
        run: |
          yarn rw prerender --verbose
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run smoke tests on 'rw dev', 'rw serve', 'rw storybook'
        working-directory: ./tasks/smoke-test
        run: npx playwright test --project replay-chromium --reporter=@replayio/playwright/reporter,line
        env:
          PROJECT_PATH: ${{ steps.setup_test_project.outputs.test_project_path }}
          REDWOOD_DISABLE_TELEMETRY: 1
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: Smoke test / ubuntu-latest / node 16 latest
          RECORD_REPLAY_NO_RECORD: 1
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
  original:
    needs: check
    runs-on: ubuntu-latest
    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1
      # This makes sure that playwright dependencies are cached in node_modules.
      PLAYWRIGHT_BROWSERS_PATH: 0
    outputs:
     duration: ${{steps.end.outputs.duration}}
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Setup job
        uses: ./.github/actions/setup_job
        with:
          node-version: 16

      - name: 🌲 Setup test project
        id: setup_test_project
        uses: ./.github/actions/setup_test_project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Run `rw build` without prerender
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run `rw prerender`
        run: |
          yarn rw prerender --verbose
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Set test start
        if: always()
        id: start
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Run smoke tests on 'rw dev', 'rw serve', 'rw storybook'
        working-directory: ./tasks/smoke-test
        run: npx playwright test --project chromium
        env:
          PROJECT_PATH: ${{ steps.setup_test_project.outputs.test_project_path }}
      - name: Set duration in output
        if: always()
        id: end
        run: echo "duration=$((`date +%s` - ${{ steps.start.outputs.time }}))" >> $GITHUB_OUTPUT

  upload-benchmarks:
    name: Upload benchmarks
    runs-on: ubuntu-latest
    needs: [record, original]
    if: always()
    steps:
      - run: |
          echo "Original Duration: ${{ needs.original.outputs.duration }}"
          echo "Record Duration: ${{ needs.record.outputs.recordDuration }}"
          echo "Upload Duration: ${{ needs.record.outputs.uploadDuration }}"
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://telemetry.replay.io"
          configuration: '{ "method": "POST", "body": {"event": "Webhook", "source": "metrics", "name": "action-finished", "project": "redwood", "originalDuration": "${{ needs.original.outputs.duration }}", "recordDuration": "${{ needs.record.outputs.recordDuration }}", "uploadDuration": "${{ needs.record.outputs.uploadDuration }}"} }'
