name: E2E Test
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  check:
    # needs: only-doc-changes
    # if: needs.only-doc-changes.outputs.only-doc-changes == 'false'
    name: ✅ Check constraints, dependencies, and package.json's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
        working-directory: ./tasks/check

      - name: ✅ Check constraints, dependencies, and package.json's
        uses: ./tasks/check

  smoke-test:
    needs: check
    strategy:
      matrix:
        node-version: [14, 16]
        record: ["record", "no-record"]
      fail-fast: false
    name: 👀 Smoke test / ubuntu-latest / node ${{ matrix.node-version }} / ${{ matrix.record }}
    runs-on: ubuntu-latest
    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1
      # This makes sure that playwright dependencies are cached in node_modules.
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Setup job
        uses: ./.github/actions/setup_job
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🌲 Setup test project
        id: setup_test_project
        uses: ./.github/actions/setup_test_project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium && npx @replayio/playwright install

      - name: Run `rw build` without prerender
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run `rw prerender`
        run: |
          yarn rw prerender --verbose
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run smoke tests on 'rw dev', 'rw serve', 'rw storybook'
        working-directory: ./tasks/smoke-test
        run: npx playwright test --project replay-chromium --reporter=@replayio/playwright/reporter,line
        env:
          PROJECT_PATH: ${{ steps.setup_test_project.outputs.test_project_path }}
          REDWOOD_DISABLE_TELEMETRY: 1
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: Smoke test / ubuntu-latest / node ${{ matrix.node-version }} latest
          RECORD_REPLAY_NO_RECORD: ${{ matrix.record == 'no-record' && '1' || '' }}
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
          
      - name: Upload Replays
        if: always()
        uses: replayio/action-upload@v0.4.3
        with:
          public: true
          api-key: rwk_RZ7vH8VGJKYQzYpOexaC2IdHRh3GPy0xJcLEUDobdkX
